import os
import django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ispinvoice.settings')
django.setup()

from isp_app.models import Customer, Invoice, Service, Tax
from datetime import datetime, date
from xhtml2pdf import pisa             # import python module
from isp_app.utils import render_to_pdf
from django.template.loader import get_template, render_to_string
from django.http import HttpResponse
from django.core.mail import send_mail, EmailMultiAlternatives
from django.utils.html import strip_tags
from ispinvoice import settings

date=date.today()

for customer in Customer.objects.all().filter(status='Active'):
    invoice=Invoice(customer=customer, invoice_date=date, is_first=False)
    invoice.save()
    context={'object': invoice, 'invoice': invoice, 'pk': str(invoice.id)}
    if invoice.customer.billing_company=="SKIF":
        template = get_template('invoiceshowpdf.html')
    else:
        template = get_template('invoiceshowpdfra.html')
    html = template.render(context)
    filename = str(invoice.invoice_number+" "+invoice.customer.city+" "+invoice.customer.customer_name+".pdf")
    result_file = open(filename, "w+b")

        # convert HTML to PDF
    pisa_status = pisa.CreatePDF(
                html,                # the HTML to convert
                dest=result_file)           # file handle to recieve result

        # close output file
           # close output file
    result_file.close()
    subject=str('Your Bandwidth invoice for '+invoice.get_month()+'!')
    html_content=render_to_string("email_template.html",context)
    text_content=strip_tags(html_content)

    import smtplib

# import the corresponding modules
    from email import encoders
    from email.mime.base import MIMEBase
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    port = 465
    smtp_server = "mail.skifgroup.com"
    login = "no-reply@skifgroup.com" # paste your login generated by Mailtrap
    password = "Bismillah123" # paste your password generated by Mailtrap

    subject = str('Your Bandwidth invoice for '+invoice.get_month()+'!')
    sender_email = "no-reply@skifgroup.com"
    cc1="suleman@skifgroup.com"

    if (invoice.customer.email):
        receiver_email = str(invoice.customer.email)
    else:
        receiver_email = 'msz111@hotmail.co.uk'
    recipients = [receiver_email, 'suleman@skifgroup.com']
    message = MIMEMultipart()
    message["From"] = sender_email
    message['To'] = ", ".join(recipients)
    message["Subject"] = subject

    # Add body to email
    body = render_to_string("email_template.html",context)
    message.attach(MIMEText(body, "html"))

    filename = str(invoice.invoice_number+" "+invoice.customer.city+" "+invoice.customer.customer_name+".pdf")
    # Open PDF file in binary mode

    # We assume that the file is in the directory where you run your Python script from
    with open(filename, "rb") as attachment:
        # The content type "application/octet-stream" means that a MIME attachment is a binary file
        part = MIMEBase("application", "octet-stream")
        part.set_payload(attachment.read())

    # Encode to base64
    encoders.encode_base64(part)

    # Add header
    part.add_header(
        "Content-Disposition",
        f"attachment; filename= {filename}",
    )

    # Add attachment to your message and convert it to string
    message.attach(part)
    text = message.as_string()

    # send your email
    with smtplib.SMTP_SSL("mail.skifgroup.com", 465) as server:
        server.login(login, password)
        server.sendmail(
            sender_email, recipients, text
        )
