# Generated by Django 3.0.8 on 2020-11-16 06:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import isp_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200)),
                ('address', models.CharField(max_length=350)),
                ('billing_address', models.CharField(max_length=350)),
                ('city', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=200)),
                ('colocation', models.CharField(max_length=150)),
                ('ntn_cnic', models.CharField(max_length=200)),
                ('taxpayer_status', models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default=None, max_length=100)),
                ('taxpayer_name', models.CharField(max_length=200)),
                ('connection_date', models.DateField()),
                ('billing_company', models.CharField(choices=[('SKIF', 'SKIF'), ('RA', 'RA')], default=None, max_length=100)),
                ('cnic_pic', models.ImageField(default=None, upload_to='gallery')),
                ('otc', models.IntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Disconnected', 'Disconnected')], default='Active', max_length=100)),
                ('ipaddr', models.CharField(max_length=200)),
                ('customer_id', models.CharField(blank=True, default=isp_app.models.Customer.increment_customer_id, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=100)),
                ('tax_percentage', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tax_type', models.CharField(choices=[('Simple', 'Simple'), ('Compound', 'Compound')], default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('CIR', 'CIR'), ('Shared', 'Shared'), ('Business Plus', 'Business Plus'), ('L2 Data', 'L2 Data'), ('VPS', 'VPS'), ('Hosted Server', 'Hosted Server'), ('Live IP', 'Live IP'), ('Rental', 'Rental')], default=None, max_length=100)),
                ('service_qunatity', models.FloatField()),
                ('service_unit_price', models.FloatField()),
                ('service_tax', models.ManyToManyField(blank=True, to='isp_app.Tax')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceOTC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, default=isp_app.models.InvoiceOTC.increment_invoice_number, max_length=500, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='isp_app.Customer')),
                ('invoice_created_by', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('invoice_date', models.DateField(default=datetime.date.today, verbose_name='Invoice Date')),
                ('invoice_number', models.CharField(blank=True, default=isp_app.models.Invoice.increment_invoice_number, max_length=500, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='isp_app.Customer')),
                ('invoice_created_by', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FirstInvoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('invoice_date', models.DateField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, default=isp_app.models.FirstInvoice.increment_invoice_number, max_length=500, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='isp_app.Customer')),
                ('invoice_created_by', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='service_subscribed',
            field=models.ManyToManyField(to='isp_app.Service'),
        ),
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_updated', models.DateField(auto_now=True)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_number', models.CharField(blank=True, default=isp_app.models.ApplicationForm.increment_application_number, max_length=500, null=True)),
                ('application_created_by', models.ForeignKey(default=1, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='isp_app.Customer')),
            ],
        ),
    ]
